database:
  url: "${DATABASE_URL}"
  pool_size: 20

redis:
  url: "${REDIS_URL}"

telegram:
  token: "${BOT_TOKEN}"
  admin_chat_id: "${ADMIN_CHAT_ID}"
  admin_users: ${ADMIN_USERS}

# Современная детекция спама
spam_detection:
  ensemble:
    spam_threshold: 0.7
    high_confidence_threshold: 0.85
    auto_ban_threshold: 0.9
    max_processing_time: 1.5
    enable_early_exit: true
    
    # RUSpam настройки
    use_ruspam: true
    ruspam_min_length: 15
    russian_threshold: 0.4
    
    # BotHub настройки
    bothub_min_length: 10
    use_bothub_fallback: true
    bothub_timeout: 60.0
    bothub_min_ruspam_confidence: 0.2

# RUSpam production
ruspam:
  model_name: "RUSpam/spamNS_v1"
  min_confidence: 0.7
  cache_results: true
  cache_ttl: 1800


bothub:
  model: "gpt-5-nano"
  max_tokens: 1000
  temperature: 0.0
  timeout: 60.0
  max_retries: 2
  retry_delay: 1.0

# Внешние API
external_apis:
  cas:
    api_url: "https://api.cas.chat/check"
    timeout: 5
    cache_ttl: 3600  # 1 час
    retry_attempts: 2

# Модерация
moderation:
  auto_ban_threshold: 0.85
  auto_restrict_threshold: 0.70
  delete_recent_messages: true
  recent_messages_hours: 1
  aggressive_cleanup: true

# Логирование
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/antispam-bot-dev.log"
  structured: true

# HTTP Server
http_server:
  enabled: true
  host: "0.0.0.0"
  port: 8080
  workers: 4
  cors_enabled: false
  cors_origins: []

# API настройки
api:
  rate_limit:
    default_requests_per_minute: 60
    default_requests_per_day: 5000
    burst_limit: 10
  
  auth:
    jwt_secret: "${JWT_SECRET:-dev_secret_change_in_production}"
    jwt_algorithm: "HS256"
    access_token_expire_minutes: 30
    refresh_token_expire_days: 7
  
  features:
    batch_detection: true
    usage_analytics: true

# Метрики и мониторинг
metrics:
  enabled: true
  prometheus_port: 9090
  collect_detailed: true

# Производительность
performance:
  max_concurrent_checks: 20
  detection_timeout: 6
  cache_detection_results: 300
  rate_limit_per_user: 10

# Биллинг OpenRouter
openrouter_billing:
  retention_days: 90
  enable_redis_cache: true

# Настройки разработки
dev_settings:
  reload_config: false
  debug_mode: true
  mock_external_apis: false
  test_mode: false
  save_detection_details: true