database:
  url: "${DATABASE_URL}"
  pool_size: 20

redis:
  url: "${REDIS_URL}"

telegram:
  token: "${BOT_TOKEN}"
  admin_chat_id: "${ADMIN_CHAT_ID}"
  admin_users: ${ADMIN_USERS}

# Строгие настройки для production
spam_detection:
  ensemble:
    spam_threshold: 0.7
    high_confidence_threshold: 0.85
    auto_ban_threshold: 0.9
    max_processing_time: 1.5
    enable_early_exit: true
    
    # RUSpam настройки
    use_ruspam: true
    ruspam_min_length: 15
    russian_threshold: 0.4
    
    # BotHub настройки
    bothub_min_length: 10
    use_bothub_fallback: true
    bothub_timeout: 60.0
    bothub_min_ruspam_confidence: 0.2

# RUSpam production
ruspam:
  model_name: "RUSpam/spamNS_v1"
  min_confidence: 0.7
  cache_results: true
  cache_ttl: 1800


# BotHub
bothub:
  model: "gpt-5-nano"
  max_tokens: 300
  temperature: 0.0
  timeout: 60.0
  max_retries: 1
  retry_delay: 1.0

# Внешние API
external_apis:
  cas:
    api_url: "https://api.cas.chat/check"
    timeout: 3
    cache_ttl: 7200
    retry_attempts: 1

# Строгая модерация
moderation:
  auto_ban_threshold: 0.95
  auto_restrict_threshold: 0.8
  delete_recent_messages: true
  recent_messages_hours: 2
  aggressive_cleanup: true

# Production логирование
logging:
  level: "WARNING"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/antispam-bot-prod.log"
  structured: true

# HTTP Server production
http_server:
  enabled: true
  host: "0.0.0.0"
  port: 8080
  workers: 4
  cors_enabled: false
  cors_origins: []

# API production
api:
  rate_limit:
    default_requests_per_minute: 30
    default_requests_per_day: 2000
    burst_limit: 5
  
  auth:
    jwt_secret: "${JWT_SECRET}"
    jwt_algorithm: "HS256"
    access_token_expire_minutes: 15
    refresh_token_expire_days: 3
  
  features:
    batch_detection: true
    usage_analytics: true

# Метрики production
metrics:
  enabled: true
  prometheus_port: 9090
  collect_detailed: false

# Производительность production
performance:
  max_concurrent_checks: 20
  detection_timeout: 1.5
  cache_detection_results: 600
  rate_limit_per_user: 10

# Биллинг OpenRouter
openrouter_billing:
  retention_days: 365
  enable_redis_cache: true

# Безопасность
security:
  enable_ip_whitelist: true
  allowed_ips: ["${ALLOWED_IPS}"]
  enable_request_signing: true
  max_request_size: 1048576
  enable_ddos_protection: true